# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 053be5f3cb8750e70b396f31fafa3781a06e32952110636ca73bd8243934ce83055ea7577bfc283938297073d75260beffff60d4f8616ed66c38e8305ec50f2c

test:
  secret_key_base: cc9021c528ff4dc921bf85243cc2808c5f5a427098fb6f9e5b3e39915a48794015149c38b1d67d251acb18dcdbe9e76a8886df3be9bd3f015017446156c4e335

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
